---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 24h
  url: https://openebs.github.io/openebs
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: "4.1.1"
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: openebs
      interval: 12h
  values:
    engines.local.lvm.enabled: false
    engines.local.zfs.enabled: false
    mayastor.csi.node.initContainers.enabled: false
    mayastor.etcd.localpvScConfig.basePath: /var/local/openebs/localpv-hostpath/etcd
    mayastor.loki-stack.localpvScConfig.basePath: /var/local/openebs/localpv-hostpath/loki
