apiVersion: v1
kind: Namespace
metadata:
  name: firefly-iii
  labels:
    toolkit.fluxcd.io/tenant: dev-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: firefly-iii
  namespace: firefly-iii
spec:
  interval: 5m
  url: https://firefly-iii.github.io/kubernetes
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly
  namespace: firefly-iii
spec:
  releaseName: firefly
  chart:
    spec:
      chart: firefly-iii
      sourceRef:
        kind: HelmRepository
        name: firefly-iii
  interval: 50m
  timeout: 10m
  install:
    remediation:
      retries: 3
  values:
    config:
      env:
        DB_HOST: "firefly-db"
        DB_USERNAME: firefly
        DB_CONNECTION: pgsql
    secrets:
      env:
        DB_PASSWORD: "JXySMM0OhUCmTN60psrf8"
    ingress:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
      - firefly.codeplating.com
      tls:
        - secretName: firefly-iii-tls
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly-db
  namespace: firefly-iii
spec:
  releaseName: firefly-db
  chart:
    spec:
      chart: firefly-db
      sourceRef:
        kind: HelmRepository
        name: firefly-iii
  interval: 50m
  timeout: 10m
  install:
    remediation:
      retries: 3
  values:
    storage:
      accessModes: ReadWriteOnce
      class: local-path
    backup:
      destination: pvc
      pvc:
        class: local-path
    configs:
      DBUSER: firefly
      PGPASSWORD: "JXySMM0OhUCmTN60psrf8"
      POSTGRES_PASSWORD: "JXySMM0OhUCmTN60psrf8"
      DBHOST: firefly-db
    service:
      type: ClusterIP
      port: 8080
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly-importer
  namespace: firefly-iii
spec:
  releaseName: firefly-importer
  chart:
    spec:
      chart: importer
      sourceRef:
        kind: HelmRepository
        name: firefly-iii
  interval: 50m
  timeout: 10m
  install:
    remediation:
      retries: 3
---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: firefly-iii-tls
#  namespace: firefly-iii
#spec:
#  secretName: firefly-iii-tls      # <===  Name of secret where the generated certificate will be stored.
#  dnsNames:
#    - "firefly.codeplating.com"
#  issuerRef:
#    name: letsencrypt-prd
#    kind: ClusterIssuer

